web_os:
    resource: "@WebOsBundle/Resources/config/routing.yml"
    prefix:   /

web_os:
    resource: "@webOsBundle/Resources/config/routing.yml"
    prefix:   /

web_navigateur:
    resource: "@WebNavigateurBundle/Resources/config/routing.yml"
    prefix:   /

web_forfait:
    resource: "@WebForfaitBundle/Resources/config/routing.yml"
    prefix:   /

analatica_regex:
    resource: "@AnalaticaRegexBundle/Resources/config/routing.yml"
    prefix:   /

analatica_forfait:
    resource: "@AnalaticaForfaitBundle/Resources/config/routing.yml"
    prefix:   /

analatica_navigateur:
    resource: "@AnalaticaNavigateurBundle/Resources/config/routing.yml"
    prefix:   /

navigateur:
    resource: "@AnalaticaNavigateurBundle/Resources/config/routing/navigateur.yml"
    prefix:   /navig

analatica_os:
    resource: "@AnalaticaOsBundle/Resources/config/routing.yml"
    prefix:   /

analatica_user_agent:
    resource: "@AnalaticaUserAgentBundle/Resources/config/routing.yml"
    prefix:   /

analatica_user:
    resource: "@AnalaticaUserBundle/Resources/config/routing.yml"
    prefix:   /
fos_oauth_server_token:
        resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

acme_oauth_server_auth_login:
    pattern:  /oauth/v2/auth_login
    defaults: { _controller: AnalaticaUserBundle:Security:login }

acme_oauth_server_auth_login_check:
    pattern:  /oauth/v2/auth_login_check
    defaults: { _controller: AnalaticaUserBundle:Security:loginCheck }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile