parameters:
#    web_forfait.example.class: Web\ForfaitBundle\Example

services:
#    web_forfait.example:
#        class: %web_forfait.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
