navigateur_show:
  resource: Web\NavigateurBundle\Controller\NavigateurController
  methods:   [Get]

Navigateur_azerty:
  resource: Web\NavigateurBundle\Controller\DefaultController
  methods:   [Get]