parameters:
#    web_navigateur.example.class: Web\NavigateurBundle\Example

services:
#    web_navigateur.example:
#        class: %web_navigateur.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
