analatica_forfait_homepage:
    path:     /hello/{name}
    defaults: { _controller: AnalaticaForfaitBundle:Default:index }

analatica_forfait_homepage:
    path:     /forfait
    defaults: { _controller: AnalaticaForfaitBundle:Forfait  }


analatica_forfait_homepage:
    path:     /hello/{name}
    defaults: { _controller: AnalaticaForfaitBundle:Default:index }

