parameters:
#    analatica_forfait.example.class: Analatica\ForfaitBundle\Example

services:
#    analatica_forfait.example:
#        class: %analatica_forfait.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
